### PR TITLE
Updated for Django 1.9

### PR DESCRIPTION
**Pull request by dakusan**
Added some code to account for removed functions in the current version of django.

I can confirm this works on Django 1.9.2.

Unfortunately, I am, not able at the moment to test on older versions, so I can't confirm if the code works for them.

The most likely possibility where I expect this might not work is the line `get_models=models.get_models` . It and the `except:` line above it might need to just be removed.

### CODE REVIEW

**Comment by dakusan** [comment]
I undid all of my changes and resubmitted the patch, and it still isn't passing. So the problem is with the build processor, not the changes.

**Comment by WoLpH** [comment]
Hi @dakusan,

First of all, thanks for the help. It's greatly appreciated :)
As for the build processor, it seems that it's partially broken due to upstream changes (Django updates) which make it a bit harder to test. I'll try to get everything up and running again so merging your changes won't be a problem :)

The easiest way to test multiple environments is by using tox btw, it automatically creates a virtual environment with specific Python versions and Django versions and tests all of them.

**Comment by dakusan** [comment]
No prob and no rush. I figured that's what it was right when I got back the errors, but I wanted to make sure. It doesn't bother me if it since in my pull request list for a while :-) Thanks for the quick response.

And also thanks for the recommendation about python version checking. I definitely need to look into getting that set up for my other projects.

**Comment by WoLpH** [comment]
It took some time but I think I have it properly merged now :)

As for the amends, I don't think they give alerts. Only the creation of the pull request itself.

**Comment by dakusan** [comment]
Great, thanks! I'll go ahead and close the pull request then. Also, thanks for letting me know about the pull request alert stuff. Still feeling my way around github.

**Pull request closed without merging**
